name: Benchmark is up to date
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        shell: bash
        run: |
          make install

      - name: Run tests
        shell: bash
        run: |
          make check-benchmark-is-up-to-date
