# creates the documentation on pushes it to the gh-pages branch
name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Build and Deploy
        if: github.event_name == 'push'
        run: uv run mkdocs gh-deploy --force
      
      - name: Build
        if: github.event_name == 'pull_request'
        run: make build-docs